#!/bin/bash
#------------------------------------------------------------------------------#
sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com

sudo pacman-key --lsign-key 3056513887B78AEB

sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'

sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

#----------------------------------------------------------------------------------------#

sudo sed -i 's/^#\[custom]/\[chaotic-aur\]/' /etc/pacman.conf

sudo sed -i "s/^#SigLevel = Optional TrustAll/Include = \/etc\/pacman.d\/chaotic-mirrorlist/" /etc/pacman.conf

#----------------------------------------------------------------------------------------#

yay -S --noconfirm otf-takao

sudo pacman -Syyuu --noconfirm ananicy-cpp cachyos-ananicy-rules-git zramswap hardinfo antimicrox ttf-ms-fonts system-monitoring-center onlyoffice-bin gconf

yay -S --noconfirm grub-customizer-git stacer-bin sddm-config-editor-git ttf-tahoma lib32-gconf python-proxy_tools python-pywebview

git clone https://github.com/linuxshef/shefos.git ; cd shefos/grub-snap ; make install


#----------------------------------------------------------------------------------------#

sudo mkinitcpio -P
sudo grub-mkconfig -o /boot/grub/grub.cfg
sudo systemctl daemon-reload
sudo systemctl enable bluetooth
sudo systemctl enable cups
sudo systemctl enable libvirtd
sudo systemctl enable systemd-timesyncd
sudo systemctl enable systemd-resolved
sudo systemctl enable fstrim.timer
sudo fstrim -v /
sudo systemctl enable ananicy-cpp
sudo systemctl enable zramswap
sudo systemctl enable irqbalance
sudo echo "ZRAM_COMPRESSION_ALGO=zstd" | tee -a /etc/zramswap.conf
sudo systemctl enable firewalld
sudo systemctl enable cpupower
sudo systemctl enable haveged
sudo systemctl enable optimus-manager
sudo systemctl enable --now dbus-broker.service
sudo timeshift --check
sudo systemctl enable NetworkManager
sudo systemctl enable sddm --force
sudo firewall-cmd --permanent --zone=public --add-service=kdeconnect
sudo firewall-cmd --reload

reboot
