#!/bin/bash
clear
read -p "









                                  -> Введите значение :  " text


sed -i s/"git commit -m 'txt'"/"git commit -m '$text'" /g config/git_update

./config/git_update
