#!/bin/bash
clear

touch config/tmp

read -p "









                                  -> Введите значение :  " text
echo "git commit -m '$text'" > config/tmp

git add *

source config/tmp

git push

rm config/tmp
