#!/bin/bash

sudo journalctl --vacuum-size=1M
sudo journalctl --verify
sudo mkinitcpio -p linux-xanmod
sudo mkinitcpio -p linux-xanmod
sudo grub-mkconfig -o /boot/grub/grub.cfg
sudo systemctl enable bluetooth
sudo systemctl enable cups
sudo systemctl enable libvirtd
sudo systemctl enable systemd-timesyncd
sudo systemctl enable systemd-resolved
sudo systemctl enable fstrim.timer
sudo fstrim -v /
sudo systemctl enable ananicy-cpp
sudo systemctl enable zramswap
sudo systemctl enable irqbalance
sudo swapoff -a
sudo echo "ZRAM_COMPRESSION_ALGO=zstd" | tee -a /etc/zramswap.conf
sudo systemctl enable firewalld
sudo systemctl enable cpupower
sudo systemctl enable haveged
sudo systemctl enable --now dbus-broker.service
sudo timeshift --check
sudo SKIP_AUTOSNAP=1 systemctl enable NetworkManager
sudo SKIP_AUTOSNAP=1 systemctl enable sddm --force
sudo SKIP_AUTOSNAP=1 firewall-cmd --permanent --zone=public --add-service=kdeconnect
sudo SKIP_AUTOSNAP=1 firewall-cmd --reload

reboot
