#!/bin/bash








git clone https://github.com/linuxshef/shefos.git

cd shefos/grub-snap

sudo make install

sudo timeshift --check

cd ..

cd ..

echo '


             please reboot PC / перезагрузите ПК




'

rm -Rf shefos


